{
    "name": "Amanat: Переводы",
    "version": "18.0.2.0",
    "summary": "Amanat",
    "description": "Модуль проекта Amanat",
    "author": "IncubeAI (Мирас, Комрад и Эдуард)",
    "category": "Amanat",
    "depends": ["base", "mail", "mail_bot", "base_automation", "web", "base_setup", "bus", "chatter_attachments_manager"],
    "data": [
        "templates/webclient.xml",
        "views/res_users.xml",
        "views/res_config_settings.xml",
        # 1) Сначала объявляем группы
        "security/security_groups.xml",
        # 2) Затем прописываем права на модели
        "security/ir.model.access.csv",
        # 3) Затем правила доступа (record rules). Можно до или после menu.xml,
        #    главное, чтобы security_groups.xml был до него.
        "security/record_rules.xml",
        # 3) Скрываем системные приложения
        # 4) Потом представления для моделей
        "views/automation_views.xml",
        "views/contragent_views.xml",
        "views/activity_views.xml",
        "views/payer_views.xml",
        "views/transfer_views.xml",
        "views/wallet_views.xml",
        "views/order_views.xml",
        "views/money_views.xml",
        "views/reconciliation_date_range_wizard_views.xml",
        "views/reconciliation_views.xml",
        "views/ranges_views.xml",
        "views/rates_views.xml",
        "views/writeoff_views.xml",
        "views/conversion_views.xml",
        "views/extract_delivery_views.xml",
        "views/country_views.xml",
        "views/zayavka_date_range_wizard_views.xml",
        "views/zayavka_kassa_wizard_views.xml",
        "views/zayavka_views.xml",
        "views/reserve_views.xml",
        "views/kassa_ivan_views.xml",
        "views/kassa_2_views.xml",
        "views/kassa_3_views.xml",
        "views/price_list_partners_views.xml",
        "views/price_list_payer_carrying_out_views.xml",
        "views/payment_order_rule_views.xml",
        "views/money_cost_rule_views.xml",
        "views/expense_rule_views.xml",
        "views/price_list_payer_profit_views.xml",
        "views/tasks_views.xml",
        "views/payment_views.xml",
        "views/gold_deal_views.xml",
        "views/partner_gold_views.xml",
        "views/extracts_views.xml",
        "views/sverka_files_views.xml",
        "views/kassa_files_views.xml",
        "views/period_views.xml",
        "views/investment_views.xml",
        "views/manager_views.xml",
        "views/test_realtime_views.xml",
        "views/dashboard_views.xml",
        "views/analytics_dashboard_views.xml",
        "views/zayavka_fiks_dashboard_views.xml",
        "views/contragent_gold_view.xml",
        "views/swift_api_config_views.xml",
        "views/signature_library_views.xml",
        "views/zayavka_signature_views.xml",
        # Calculator views
        "views/calculator_50_usd_views.xml",
        "views/calculator_fixed_fee_views.xml",
        "views/calculator_125_usd_views.xml",
        "views/welcome_views.xml",
        "views/menu.xml",
        # 6) Остальные файлы
        "data/transfer_sequence.xml",
        "data/ranges_sequence.xml",
        "data/rates_sequence.xml",
        "data/zayavka_sequence.xml",
        "data/kassa_ivan_sequence.xml",
        "data/kassa_2_sequence.xml",
        "data/kassa_3_sequence.xml",
        "data/gold_deal_sequence.xml",
        "data/partner_gold_sequence.xml",
        "data/order_sequence.xml",
        "data/conversion_sequence.xml",
        "data/reserve_sequence.xml",
        "data/investment_sequence.xml",
        "data/cron_accrue_interest.xml",
        "data/cron_update_money_states.xml",
        "data/amanat_writeoff_sequence.xml",
        "data/extract_delivery_sequence.xml",
        "data/kassa_files_sequence.xml",
        "data/dashboard_data.xml",
        "data/analytics_dashboard_data.xml",
        "data/zayavka_fiks_dashboard_data.xml",
        "data/demo_signature_library.xml",
        "data/ilzira_user_setup.xml",
        "data/treasurer_users_setup.xml",
        "data/update_ilzira_group.xml",
        # "data/mass_editing_actions.xml",
    ],
    "assets": {
        "web._assets_primary_variables": [
            "amanat/static/src/scss/variables.scss",
        ],
        "web._assets_backend_helpers": [
            "amanat/static/src/scss/mixins.scss",
        ],
        "web.assets_web_dark": [
            (
                "after",
                "amanat/static/src/scss/variables.scss",
                "amanat/static/src/scss/variables.dark.scss",
            ),
        ],
        "web.assets_backend": [
            # "amanat/static/src/js/debug_realtime.js",
            # "amanat/static/src/js/bus_diagnostic.js",
            # "amanat/static/src/js/realtime_test_helper.js",
            # "amanat/static/src/js/test_buttons.js",
            # "amanat/static/src/js/real_time_interaction.js",
            # "amanat/static/src/js/list_view_enhanced.js",
            # "amanat/static/src/js/fixed_columns_calculator.js",
            # "amanat/static/src/js/writeoff_context.js",
            "amanat/static/src/js/menu_sections_handler.js",
            "amanat/static/src/js/welcome_screen.js",
            "amanat/static/src/js/list_view_numbering.js",
            "amanat/static/src/js/chatter_toggle.js",
            "amanat/static/src/js/swift_commands.js",
            "amanat/static/src/js/amanat_dashboard.js",
            "amanat/static/src/js/analytics_dashboard.js",
            "amanat/static/src/js/zayavka_fiks_dashboard.js",
            "amanat/static/src/xml/amanat_dashboard.xml",
            "amanat/static/src/xml/analytics_dashboard.xml",
            "amanat/static/src/xml/zayavka_fiks_dashboard.xml",
            "amanat/static/src/xml/welcome_screen.xml",
            (
                "after",
                "web/static/src/webclient/webclient.js",
                "amanat/static/src/webclient/webclient.js",
            ),
            (
                "after",
                "web/static/src/webclient/webclient.xml",
                "amanat/static/src/webclient/webclient.xml",
            ),
            (
                "after",
                "web/static/src/webclient/webclient.js",
                "amanat/static/src/webclient/menus/app_menu_service.js",
            ),
            (
                "after",
                "web/static/src/webclient/webclient.js",
                "amanat/static/src/webclient/appsbar/appsbar.js",
            ),
            # (
            #     "after",
            #     "web/static/src/webclient/webclient.js",
            # ),
            "amanat/static/src/webclient/webclient.scss",
            "amanat/static/src/webclient/appsbar/appsbar.xml",
            "amanat/static/src/webclient/appsbar/appsbar.scss",
            "amanat/static/src/css/style.css",
            "amanat/static/src/css/menu_sections_handler.css",
            "amanat/static/src/css/welcome_screen.css",
            "amanat/static/src/css/realtime_highlight.css",
            "amanat/static/src/css/amanat_dashboard.css",
            "amanat/static/src/css/dashboard_charts_compact.css",
            "amanat/static/src/css/attachment_preview.css",
            "amanat/static/src/scss/analytics_dashboard.scss",
            "amanat/static/src/scss/zayavka_fiks_dashboard.scss",
            "amanat/static/src/js/attachment_preview.js",
            "amanat/static/src/js/attachment_preview_modal.js",
            "amanat/static/src/js/attachment_widget_extension.js",
            "amanat/static/src/js/sverka_files_preview.js",
            "amanat/static/src/js/action_handler.js",
            "amanat/static/src/js/kassa_filter_handler.js",
            "amanat/static/src/xml/attachment_preview.xml",
            # "amanat/static/src/css/calculator_background.css",
            # "amanat/static/src/js/calculator_background.js",
        ],
    },
    "external_dependencies": {
        "python": ["pandas", "python-docx", "openpyxl", "xlrd"]
    },
    "installable": True,
    "application": True,
}
